language: node_js
node_js: stable

env:
  - ROUTER_BASE=/nuxt-with-paper-dashboard/

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - "npm run generate"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target-branch: gh-pages
  local_dir: dist
  on:
    branch: master
